ftp: 224
workouts:
  - name: Carson
    description: "Sweet Spot. Intevals. 7x5-7-minute intervals between 88-94% FTP totaling 42 minutes of Sweet Spot work. Intervals are separated by 2-minute recoveries."
    steps:
      - time: "4:00"
        ftp_percentage: "50%"
      - time: "4:00"
        ftp_percentage: "70%"
      - time: "4:00"
        ftp_percentage: "90%"
      - time: "5:00"
        ftp_percentage: "40%"
      - time: "5:00"
        ftp_percentage: "88%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "6:00"
        ftp_percentage: "92%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "7:00"
        ftp_percentage: "90%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "6:00"
        ftp_percentage: "94%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "5:00"
        ftp_percentage: "88%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "6:00"
        ftp_percentage: "92%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "7:00"
        ftp_percentage: "91%"
      - time: "5:00"
        ftp_percentage: "40%"

  - name: Ochsenhorn
    description: "Vo2max. 4x4.5-minute intervals at 106% FTP. Each full interval is separated by a 9 minute and 40 second recovery valley."
    steps:
      - time: "1:30"
        ftp_percentage: "50%"
      - time: "2:00"
        ftp_percentage: "72%"
      - time: "2:00"
        ftp_percentage: "96%"
      - time: "5:30"
        ftp_percentage: "50%"
      - time: "4:30"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"
      - time: "4:30"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"
      - time: "4:30"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"
      - time: "4:30"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"

  - name: Sphinx
    description: "Warm up then perform 5x30-second intervals increasing effort each time. Then, complete 2x10-minute intervals just above threshold with 5 minutes recovery between intervals."
    steps:
      - time: "5:00"
        ftp_percentage: "50%"
      - time: "5:00"
        ftp_percentage: "60%"
      - time: "5:00"
        ftp_percentage: "70%"
      - time: "5:00"
        ftp_percentage: "70%"
      - time: "0:30"
        ftp_percentage: "90%"
      - time: "0:30"
        ftp_percentage: "65%"
      - time: "0:30"
        ftp_percentage: "92%"
      - time: "0:30"
        ftp_percentage: "65%"
      - time: "0:30"
        ftp_percentage: "95%"
      - time: "0:30"
        ftp_percentage: "65%"
      - time: "0:30"
        ftp_percentage: "97%"
      - time: "0:30"
        ftp_percentage: "65%"
      - time: "0:30"
        ftp_percentage: "100%"
      - time: "0:30"
        ftp_percentage: "65%"
      - time: "5:00"
        ftp_percentage: "70%"
      - time: "10:00"
        ftp_percentage: "105%"
      - time: "5:00"
        ftp_percentage: "50%"
      - time: "10:00"
        ftp_percentage: "105%"
      - time: "10:00"
        ftp_percentage: "50%"
