ftp: 224
workouts:
  - name: Diamond
    description: "Sweetspot. 1h. Diamond is composed of 4x9-minute sets of varied VO2 Max/Anaerobic (105-135% FTP) bridging efforts ranging from 30 seconds to 2-minutes with varied intervals at Sweet Spot/Threshold (90-95% FTP) in between."
    steps:
      - time: "2:00"
        ftp_percentage: "50%"
      - time: "2:00"
        ftp_percentage: "65%"
      - time: "1:30"
        ftp_percentage: "90%"
      - time: "0:30"
        ftp_percentage: "120%"
      - time: "3:00"
        ftp_percentage: "40%"

      - time: "2:00"
        ftp_percentage: "90%"
      - time: "1:00"
        ftp_percentage: "115%"
      - time: "2:00"
        ftp_percentage: "95%"
      - time: "1:00"
        ftp_percentage: "120%"
      - time: "3:00"
        ftp_percentage: "100%"
      - time: "5:00"
        ftp_percentage: "74%"

      - time: "3:00"
        ftp_percentage: "90%"
      - time: "0:30"
        ftp_percentage: "130%"
      - time: "2:00"
        ftp_percentage: "92%"
      - time: "0:30"
        ftp_percentage: "130%"
      - time: "1:00"
        ftp_percentage: "95%"
      - time: "0:30"
        ftp_percentage: "135%"
      - time: "1:30"
        ftp_percentage: "100%"
      - time: "4:00"
        ftp_percentage: "60%"

      - time: "2:00"
        ftp_percentage: "95%"
      - time: "2:00"
        ftp_percentage: "105%"
      - time: "2:00"
        ftp_percentage: "90%"
      - time: "2:00"
        ftp_percentage: "110%"
      - time: "1:00"
        ftp_percentage: "100%"
      - time: "3:00"
        ftp_percentage: "50%"

      - time: "3:00"
        ftp_percentage: "90%"
      - time: "0:45"
        ftp_percentage: "127%"
      - time: "3:00"
        ftp_percentage: "90%"
      - time: "0:45"
        ftp_percentage: "130%"
      - time: "1:30"
        ftp_percentage: "100%"
      - time: "5:00"
        ftp_percentage: "40%"


  - name: Diamond-4
    description: "Threshold. composed four sets of varied VO2 Max/Anaerobic (105-135% FTP) bridging efforts ranging from 30 seconds to 2 minutes with varied intervals at Sweet Spot/Threshold (90-95% FTP) in between."
    steps:
      - time: "2:00"
        ftp_percentage: "50%"
      - time: "1:30"
        ftp_percentage: "65%"
      - time: "1:30"
        ftp_percentage: "90%"
      - time: "0:30"
        ftp_percentage: "120%"
      - time: "3:00"
        ftp_percentage: "40%"

      - time: "1:30"
        ftp_percentage: "90%"
      - time: "1:00"
        ftp_percentage: "115%"
      - time: "1:30"
        ftp_percentage: "95%"
      - time: "1:00"
        ftp_percentage: "120%"
      - time: "2:30"
        ftp_percentage: "100%"
      - time: "3:00"
        ftp_percentage: "70%"

      - time: "2:30"
        ftp_percentage: "90%"
      - time: "0:30"
        ftp_percentage: "130%"
      - time: "1:30"
        ftp_percentage: "92%"
      - time: "0:30"
        ftp_percentage: "130%"
      - time: "1:00"
        ftp_percentage: "95%"
      - time: "0:30"
        ftp_percentage: "135%"
      - time: "1:30"
        ftp_percentage: "100%"
      - time: "2:00"
        ftp_percentage: "60%"

      - time: "1:30"
        ftp_percentage: "95%"
      - time: "1:30"
        ftp_percentage: "105%"
      - time: "1:30"
        ftp_percentage: "90%"
      - time: "1:30"
        ftp_percentage: "110%"
      - time: "1:00"
        ftp_percentage: "100%"
      - time: "1:00"
        ftp_percentage: "50%"

      - time: "2:00"
        ftp_percentage: "90%"
      - time: "0:45"
        ftp_percentage: "125%"
      - time: "2:00"
        ftp_percentage: "90%"
      - time: "0:45"
        ftp_percentage: "130%"
      - time: "1:30"
        ftp_percentage: "100%"
      - time: "5:00"
        ftp_percentage: "40%"
  
  - name: Kwaay
    description: "Sweet Spot. Intevals. over 60 minutes of Tempo intervals spent between 75-88% FTP with intermittent, 5.5-minute recoveries at 55% FTP."
    steps:
      - time: "8:00"
        ftp_percentage: "50%"
      - time: "8:00"
        ftp_percentage: "65%"
      - time: "11:00"
        ftp_percentage: "80%"
      - time: "5:00"
        ftp_percentage: "55%"
      - time: "11:00"
        ftp_percentage: "88%"
      - time: "5:00"
        ftp_percentage: "55%"
      - time: "11:00"
        ftp_percentage: "70%"
      - time: "5:00"
        ftp_percentage: "55%"
      - time: "11:00"
        ftp_percentage: "85%"
      - time: "10:00"
        ftp_percentage: "50%"

  - name: Yanamax
    description: "Sweet Spot. Intevals. under 60 minutes of Tempo intervals spent between 81-88% FTP with intermittent."
    steps:
      - time: "8:00"
        ftp_percentage: "50%"
      - time: "8:00"
        ftp_percentage: "65%"
      - time: "11:00"
        ftp_percentage: "82%"
      - time: "5:00"
        ftp_percentage: "55%"
      - time: "11:00"
        ftp_percentage: "88%"
      - time: "5:00"
        ftp_percentage: "55%"
      - time: "11:00"
        ftp_percentage: "81%"
      - time: "5:00"
        ftp_percentage: "55%"
      - time: "11:00"
        ftp_percentage: "88%"
      - time: "10:00"
        ftp_percentage: "50%"

  - name: Antelope -1
    description: "Sweet Spot. Intevals. 5x10-minute Sweet Spot intervals at 88% FTP with 5-minute recoveries between intervals."
    steps:
      - time: "4:00"
        ftp_percentage: "60%"
      - time: "3:00"
        ftp_percentage: "65%"
      - time: "3:00"
        ftp_percentage: "90%"
      - time: "5:00"
        ftp_percentage: "40%"
      - time: "10:00"
        ftp_percentage: "88%"
      - time: "5:00"
        ftp_percentage: "40%"
      - time: "10:00"
        ftp_percentage: "88%"
      - time: "5:00"
        ftp_percentage: "40%"
      - time: "10:00"
        ftp_percentage: "88%"
      - time: "5:00"
        ftp_percentage: "40%"
      - time: "10:00"
        ftp_percentage: "88%"
      - time: "5:00"
        ftp_percentage: "40%"
      - time: "10:00"
        ftp_percentage: "88%"
      - time: "5:00"
        ftp_percentage: "40%"

  - name: Carson
    description: "Sweet Spot. Intevals. 7x5-7-minute intervals between 88-94% FTP totaling 42 minutes of Sweet Spot work. Intervals are separated by 2-minute recoveries."
    steps:
      - time: "4:00"
        ftp_percentage: "50%"
      - time: "4:00"
        ftp_percentage: "70%"
      - time: "4:00"
        ftp_percentage: "90%"
      - time: "5:00"
        ftp_percentage: "40%"
      - time: "5:00"
        ftp_percentage: "88%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "6:00"
        ftp_percentage: "92%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "7:00"
        ftp_percentage: "90%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "6:00"
        ftp_percentage: "94%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "5:00"
        ftp_percentage: "88%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "6:00"
        ftp_percentage: "92%"
      - time: "2:00"
        ftp_percentage: "40%"
      - time: "7:00"
        ftp_percentage: "91%"
      - time: "5:00"
        ftp_percentage: "40%"

  - name: Solferino
    description: "Vo2max. 4x4 minute intervals at 106% FTP. Each full interval is separated by a 9 minute second recovery valley."
    steps:
      - time: "1:30"
        ftp_percentage: "50%"
      - time: "2:00"
        ftp_percentage: "72%"
      - time: "2:00"
        ftp_percentage: "96%"
      - time: "5:30"
        ftp_percentage: "50%"
      - time: "4:00"
        ftp_percentage: "106%"
      - time: "9:00"
        ftp_percentage: "40%"
      - time: "4:00"
        ftp_percentage: "106%"
      - time: "9:00"
        ftp_percentage: "40%"
      - time: "4:00"
        ftp_percentage: "106%"
      - time: "9:00"
        ftp_percentage: "40%"
      - time: "4:00"
        ftp_percentage: "106%"
      - time: "9:00"
        ftp_percentage: "40%"

  - name: Ochsenhorn
    description: "Vo2max. 4x4.5-minute intervals at 106% FTP. Each full interval is separated by a 9 minute and 40 second recovery valley."
    steps:
      - time: "1:30"
        ftp_percentage: "50%"
      - time: "2:00"
        ftp_percentage: "72%"
      - time: "2:00"
        ftp_percentage: "96%"
      - time: "5:30"
        ftp_percentage: "50%"
      - time: "4:30"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"
      - time: "4:30"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"
      - time: "4:30"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"
      - time: "4:30"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"
  
  - name: McMicken
    description: "Vo2max. 4x4.75-minute intervals at 106% FTP. Each full interval is separated by a 9 minute and 40 second recovery valley."
    steps:
      - time: "1:30"
        ftp_percentage: "50%"
      - time: "2:00"
        ftp_percentage: "72%"
      - time: "2:00"
        ftp_percentage: "96%"
      - time: "5:30"
        ftp_percentage: "50%"
      - time: "4:45"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"
      - time: "4:45"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"
      - time: "4:45"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"
      - time: "4:45"
        ftp_percentage: "106%"
      - time: "9:30"
        ftp_percentage: "40%"

  - name: Sphinx
    description: "Warm up then perform 5x30-second intervals increasing effort each time. Then, complete 2x10-minute intervals just above threshold with 5 minutes recovery between intervals."
    steps:
      - time: "5:00"
        ftp_percentage: "50%"
      - time: "5:00"
        ftp_percentage: "60%"
      - time: "5:00"
        ftp_percentage: "70%"
      - time: "5:00"
        ftp_percentage: "70%"
      - time: "0:30"
        ftp_percentage: "90%"
      - time: "0:30"
        ftp_percentage: "65%"
      - time: "0:30"
        ftp_percentage: "92%"
      - time: "0:30"
        ftp_percentage: "65%"
      - time: "0:30"
        ftp_percentage: "95%"
      - time: "0:30"
        ftp_percentage: "65%"
      - time: "0:30"
        ftp_percentage: "97%"
      - time: "0:30"
        ftp_percentage: "65%"
      - time: "0:30"
        ftp_percentage: "100%"
      - time: "0:30"
        ftp_percentage: "65%"
      - time: "5:00"
        ftp_percentage: "70%"
      - time: "10:00"
        ftp_percentage: "105%"
      - time: "5:00"
        ftp_percentage: "50%"
      - time: "10:00"
        ftp_percentage: "105%"
      - time: "10:00"
        ftp_percentage: "50%"
