ftp: 224
workouts:
  - name: Ochsenhorn
    description: "4x4.5-minute intervals at 106% FTP. Each full interval is separated by a 9 minute and 40 second recovery valley."
    steps:
      - time: "1:30"
        watts: "50%"
      - time: "2:00"
        watts: "72%"
      - time: "2:00"
        watts: "96%"
      - time: "5:30"
        watts: "50%"
      - time: "4:30"
        watts: "106%"
      - time: "9:30"
        watts: "40%"
      - time: "4:30"
        watts: "106%"
      - time: "9:30"
        watts: "40%"
      - time: "4:30"
        watts: "106%"
      - time: "9:30"
        watts: "40%"
      - time: "4:30"
        watts: "106%"
      - time: "9:30"
        watts: "40%"

  - name: Sphinx
    description: "Warm up then perform 5x30-second intervals increasing effort each time. Then, complete 2x10-minute intervals just above threshold with 5 minutes recovery between intervals."
    steps:
      - time: "5:00"
        watts: "50%"
      - time: "5:00"
        watts: "60%"
      - time: "5:00"
        watts: "70%"
      - time: "5:00"
        watts: "70%"
      - time: "0:30"
        watts: "90%"
      - time: "0:30"
        watts: "65%"
      - time: "0:30"
        watts: "92%"
      - time: "0:30"
        watts: "65%"
      - time: "0:30"
        watts: "95%"
      - time: "0:30"
        watts: "65%"
      - time: "0:30"
        watts: "97%"
      - time: "0:30"
        watts: "65%"
      - time: "0:30"
        watts: "100%"
      - time: "0:30"
        watts: "65%"
      - time: "5:00"
        watts: "70%"
      - time: "10:00"
        watts: "105%"
      - time: "5:00"
        watts: "50%"
      - time: "10:00"
        watts: "105%"
      - time: "10:00"
        watts: "50%"
